### ISSUE TITLE
Model creation exception results in failure with a status code error

### ISSUE THREAD

**Issue by marius-serban** [theappbusiness/TABResourceLoader#53] opened 2017-06-09 11:28 UTC
In `NetworkResponseHandler.swift`:
```swift
switch HTTPURLResponse.statusCode {
    case 200..<400:
      let parsedResult = Result<Resource.Model> {
        return try resource.model(from: data)
      }
      switch parsedResult {
      case .success(let model):
        return .success(model, HTTPURLResponse)
      case .failure:
        return .failure(.statusCodeError(statusCode: HTTPURLResponse.statusCode), HTTPURLResponse)
      }
    default:
```
Instead, another error should be returned, something about parsing/decoding failing

**Comment by deanbrindley87** [comment] 2017-10-24 11:58
@marius-serban i've just come across this problem too and agree it needs fixing. 
the problem is the `failure` case isn't capturing its `error` property and so errors that occur during the `resource.model(from: data)` method become lost.

i'll create a PR for it, thanks for raising!

**Comment by samdods** [comment] 2017-10-25 09:47
@marius-serban is this not available in the `.statusCodeCustomError` case of `enum NetworkServiceError`?

**Comment by marius-serban** [comment] 2017-10-25 10:22
@samdods in case of parsing failure, a `.statusCode` error is returned, surely this can't be right there's nothing wrong with the status code (it's 200). The `statusCodeCustomError` _could_ be used but, it's not expressing the actual error which is related to parsing.

**Comment by KaneCheshire** [comment] 2017-10-25 10:32
Agree with @marius-serban, it's

**Comment by KaneCheshire** [comment] 2017-10-25 10:32
Clicked the wrong button when commenting... sorry. :| 

What I was trying to say before foolishly clicking the wrong button, was that I agree with @marius-serban. We should leverage the expressive behaviour of `catch` in Swift which makes it clear what error occurred.

**Comment by samdods** [comment] 2017-10-25 11:33
i don't disagree with this, but for context, i just want to highlight the [PR that removed the `.couldNotParseData` case](https://github.com/theappbusiness/TABResourceLoader/pull/51/files).

**Comment by KaneCheshire** [comment] 2017-10-25 11:55
Ah I forgot about that.

**Comment by samdods** [comment] 2017-10-25 12:43
i'm going to fix this now

**Comment by samdods** [comment] 2017-10-25 12:48
i don't know what the rationale was for removing the `.couldNotParseData` case. but my proposed solution is that we add this back in.

**Comment by samdods** [comment] 2017-10-25 12:57
![](https://github.trello.services/images/mini-trello-icon.png) [TABResourceLoader: Model creation exception results in failure with a status code error](https://trello.com/c/BHcRosWb/7-tabresourceloader-model-creation-exception-results-in-failure-with-a-status-code-error)

**Comment by KaneCheshire** [comment] 2017-10-25 13:11
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #53: Model creation exception results in failure with a status code error](https://trello.com/c/lo1PMifh/13-issue-53-model-creation-exception-results-in-failure-with-a-status-code-error)

**Comment by samdods** [comment] 2017-10-25 13:55
Fixed by PR #60

Available on CocoaPods in version 7.0.0

**Closed as completed by samdods** 2017-10-25 13:55 UTC
